# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'GigyD Docker Hub'
        repository: 'gigyd/weatherapi'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)

    - task: SnykSecurityScan@1
      inputs:
        serviceConnectionEndpoint: 'GigydSnyk'
        testType: 'app'
        targetFile: 'Dockerfile'
        monitorWhen: 'always'
        failOnIssues: true